# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd071ebc5ad4e816d464b6b03082205b6824db53cf1562f3e1f2260bb59d4d54e6a50e4072bd80d7ffd0a778460a1e9a9d0147b403f7ecac2316db61c70b098

test:
  secret_key_base: 0bcbd88056d1185f0166051782da0ca6c56292bba85e5709b8c8d011f8890300ceeeff15317c150dc9e33c3d28e99a7b5ddae21427462fe7ad1ce4d8f879633a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
